### ISSUE TITLE
Error loading mod library

### ISSUE THREAD

**Issue by Codewitt** [LittlestCube/MMRecompRando#1]
I've compiled the mod and its dependencies incl. the native library (APCpp-Glue).

Placed everything into AppData\Local\Zelda64Recompiled\mods\

When starting MM I receive an error:
![image](https://github.com/user-attachments/assets/ef21256b-2562-40ff-8b03-66fc7eb0de26)

Anyway to fix this?

**Comment by LittlestCube** [comment]
Hi! 😋 I didn't expect anyone to be trying this so soon.

I'm not sure I want to create a release for this _just_ yet, so as not to cause further hubbub when I don't know if it's fully functional. If you like though, you can try to use these files:

[mods.zip](https://github.com/user-attachments/files/17371246/mods.zip)

These are the mods I'm currently using (the `mm_recomp_mod_template` mod fixes the camera issues).

**Comment by Codewitt** [comment]
Hello! First I have to say great work! I've been following the mods in development and everything recomp!

Much appreciated! Wasn't aware you needed the both. Going to give this a go now :)
